# Generated by Django 2.1.5 on 2019-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('perm', '0002_securitypersonal_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitypersonal',
            name='group',
        ),
        migrations.AddField(
            model_name='securitypersonal',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='group',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
