# Generated by Django 2.1.5 on 2019-04-12 04:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('perm', '0003_auto_20190411_1325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='securitypersonal',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supervisor',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name='securitypersonal',
            old_name='user',
            new_name='sp',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='user',
            new_name='sv',
        ),
        migrations.RemoveField(
            model_name='securitypersonal',
            name='group',
        ),
        migrations.RemoveField(
            model_name='securitypersonal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='group',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='id',
        ),
        migrations.AddField(
            model_name='securitypersonal',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
    ]
