# Generated by Django 2.1.5 on 2019-04-12 05:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('perm', '0004_auto_20190412_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('observations', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='securitypersonal',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='group_ptr',
        ),
        migrations.AlterField(
            model_name='securitypersonal',
            name='sp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perm.User'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='sv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perm.User'),
        ),
    ]
