# Generated by Django 2.1.5 on 2019-04-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('perm', '0005_auto_20190412_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='securitypersonal',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
